### ISSUE TITLE
Database not found while trying to run Web host walk through

### ISSUE THREAD

**Issue by regisoliveira** [gustavo-armenta/CookieAuthenticationSample#11]
Hello Gustavo!

When trying to run your example, I´m getting the following error when creating the test user:
Cannot attach the file 'D:\Programming\CookieAuthenticationSample-master\WebHost\App_Data\aspnet-WebHost-20131023041903.mdf' as database 'aspnet-WebHost-20131023041903'. 

I noticied that the database file isn´t in the project.

How could we solve this?

Thanks a lot!

**Comment by gustavo-armenta** [comment]
The database file is created automatically by the aspnet stack.

You could try to give the file and catalog a different name on web.config. 

Also check your machine has installed LocalDb
C:>dir /b /s sqllocaldb.exe
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\SqlLocalDB.exe
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\SqlLocalDB.exe

**Comment by regisoliveira** [comment]
Hello Gustavo!
When LocalDb has installed, everything worked as a charm!
Thanks a lot for your help and congratulations about the sample.
