### ISSUE TITLE
A query on the implementation of JavaScript client

### ISSUE THREAD

**Issue by sravikiran** [gustavo-armenta/CookieAuthenticationSample#8]
The JavaScript client example uses the UI of web host application to sign in. What is the best way to do it in a real application? Can we use token based authentication with SignalR?

**Comment by gustavo-armenta** [comment]
Here is the Bearer Token sample
https://github.com/gustavo-armenta/BearerTokenAuthenticationSample

**Comment by sravikiran** [comment]
Thanks @gustavo-armenta. I will check it.
